export const data =[
    { name: '  Trust wallet', image: '../../images/trustwallet.png' },
    { name: '  AAVE wallet', image: '../../images/aave.jpeg' },
    { name: '  Ledger wallet', image: '../../images/ledgerwallet.png' },
    { name: '  Enjin wallet', image: '../../images/Enjinwallet.png' },
    { name: '  MEW wallet', image: '../../images/mewwallet.png' },
    { name: '  Meta mask wallet', image: '../../images/metamask.png' },
    { name: '  Digitex wallet', image: '../../images/digitex.png' },
    { name: '  Coinbase wallet', image: '../../images/coinbase.png' },
    { name: '  Autherum wallet', image: '../../images/autherum.png' },
    { name: '  Portis wallet', image: '../../images/portis.png' },
    { name: '  Formatic wallet', image: '../../images/formatic.png' },
    { name: '  Exodus wallet', image: '../../images/exodus.png' },
    { name: '  Defiat wallet', image: '../../images/defiat.png' },
    { name: '  Skale wallet', image: '../../images/skale.png' },
    { name: '  Wallet connect', image: '../../images/walletconnect.jpeg' },
    { name: '  Coinomi wallet', image: '../../images/coinomi.png' },
    { name: '  Atomic wallet', image: '../../images/atomic.jpeg' },
    { name: '  Tron wallet', image: '../../images/tronwallet.png' },
    { name: '  Band protocol wallet', image: '../../images/band.png' },
    { name: '  EOS wallet', image: '../../images/eos.png' },
    { name: '  Wax wallet', image: '../../images/wax.png' },
    { name: '  Zilliqa wallet', image: '../../images/zilliqa.png' },
    { name: '  Polkadot wallet', image: '../../images/polkadot.png' },
    { name: '  Monero wallet', image: '../../images/monero.png' },
    { name: '  Klever wallet', image: '../../images/klever.jpg' },
    { name: '  Neon wallet', image: '../../images/neon.png' },
    { name: '  Theta wallet', image: '../../images/theta.png' },
    { name: '  Tomo Chain wallet', image: '../../images/tomochain.png' },
    { name: '  Jaxx wallet', image: '../../images/jaxx.png' },
    { name: '  Elrond wallet', image: '../../images/elrond.png' },
    { name: '  Bancor wallet', image: '../../images/bancor.png' },
    { name: '  1inch wallet', image: '../../images/1inch.png' },
    { name: '  Cosmos wallet', image: '../../images/cosmos.png' },
    { name: '  Moonlet wallet', image: '../../images/moonlet.png' },
    { name: '  Harmony wallet', image: '../../images/harmony.png' },
    { name: '  Tezos wallet', image: '../../images/tezos.png' },
    { name: '  Kyber Swap wallet', image: '../../images/kyberswap.png' },
    { name: '  Falcon Swap wallet', image: '../../images/falswap.png' },
    { name: '  Zilliqa wallet', image: '../../images/zilliqa.png' },
    { name: '  Kava wallet', image: '../../images/kava.png' },
    { name: '  Ocean Protocol wallet', image: '../../images/oceanprotocol.png' },
    { name: '  Hex wallet', image: '../../images/hexcom.png' },
    { name: '  Cardano wallet', image: '../../images/cardano.png' },
    { name: '  Kardia Chain wallet', image: '../../images/kardiachain.png' },
    { name: '  Octofi wallet', image: '../../images/octofi.png' },
    { name: '  Algorand wallet', image: '../../images/algorand.png' }
  ]